[tools]
java = "11.0.2"
maven = "latest"
scala = "2.12.18"
spark = "3.5.3"

[env]
SPARK_LOCAL_IP = "127.0.0.1"

[tasks.shell]
description = "Open a shell with environment configured for Spark and Scala"
run = """
spark-shell \
--num-executors 3 \
--driver-memory 5g \
--executor-memory 8g \
--conf 'spark.serializer=org.apache.spark.serializer.KryoSerializer'
"""

[tasks.spark-shell-iceberg]
description = "Open spark-shell with Apache Iceberg support"
run = """
spark-shell \
--packages org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.10.1 \
--num-executors 3 \
--driver-memory 5g \
--executor-memory 8g \
--conf 'spark.serializer=org.apache.spark.serializer.KryoSerializer' \
--conf 'spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions' \
--conf 'spark.sql.catalog.local=org.apache.iceberg.spark.SparkCatalog' \
--conf 'spark.sql.catalog.local.type=hadoop' \
--conf "spark.sql.catalog.local.warehouse=file://${PWD}/warehouse"
"""

[tasks.spark-submit-iceberg_run_1]
description = "Run spark-submit with Apache Iceberg support and app_params.properties"
run = """
spark-submit \
--class com.example.spark.FeatCalcMergeApp \
--packages org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.10.1 \
--properties-file ${PWD}/app_params.properties \
--num-executors 3 \
--driver-memory 5g \
--executor-memory 8g \
--conf 'spark.serializer=org.apache.spark.serializer.KryoSerializer' \
--conf 'spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions' \
--conf 'spark.sql.catalog.local=org.apache.iceberg.spark.SparkCatalog' \
--conf 'spark.sql.catalog.local.type=hadoop' \
--conf "spark.sql.catalog.local.warehouse=file://${PWD}/warehouse" \
${PWD}/target/calc-vp-staging-0.1.0-SNAPSHOT.jar
"""


[tasks.spark-submit-iceberg_run_2]
description = "Run spark-submit with Apache Iceberg support and app_params.properties"
run = """
spark-submit \
--class com.example.spark.FeatCalcMergeApp \
--packages org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.10.1 \
--properties-file ${PWD}/app_params2.properties \
--num-executors 3 \
--driver-memory 5g \
--executor-memory 8g \
--conf 'spark.serializer=org.apache.spark.serializer.KryoSerializer' \
--conf 'spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions' \
--conf 'spark.sql.catalog.local=org.apache.iceberg.spark.SparkCatalog' \
--conf 'spark.sql.catalog.local.type=hadoop' \
--conf "spark.sql.catalog.local.warehouse=file://${PWD}/warehouse" \
${PWD}/target/original-calc-vp-staging-0.1.0-SNAPSHOT.jar
"""
